# Generated by Django 2.2 on 2019-12-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatimage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
